# Generated by Django 5.0.6 on 2024-06-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='2220879813', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
